# Generated by Django 4.0.5 on 2022-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
